// !!! This is a file automatically generated by hipify!!!
#include <torch/extension.h>
#include <hip/hip_runtime.h>

__global__ void add_one(float* data, int n);

void add_one_launcher(torch::Tensor tensor) {
    int n = tensor.numel();
    float* data = tensor.data_ptr<float>();

    int block_size = 256;
    int grid_size = (n + block_size - 1) / block_size;

   hipLaunchKernelGGL(( add_one), dim3(grid_size), dim3(block_size), 0, 0, data, n);

    hipDeviceSynchronize();
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("add_one", &add_one_launcher, "Add one kernel (HIP)");
}
